{
  "name": "s3-sink-connector-dev",
  "config": {
    "append.late.data": "false",
    "config.storage.replication.factor": "1",
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "flush.size": "10",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": "false",
    "locale": "en",
    "metadata.max.age.ms": "1000",
    "partition.duration.ms": "86400000",
    "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "partition.field.name": "[int]",
    "path.format": "'year'=YYYY/'month'=MM/'day'=dd",
    "retry.backoff.ms": "5000",
    "rotate.interval.ms": "86400000",
    "rotate.schedule.interval.ms": "86400000",
    "s3.bucket.name": "{{S3_BUCKET}}",
    "s3.part.size": "5242880",
    "s3.region": "eu-west-2",
    "schema.compatibility": "NONE",
    "schemas.enable": "false",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "tasks.max": "1",
    "timestamp.extractor": "uk.gov.hmrc.txm.kafka.connect.storage.partitioner.FirstMatchTimestampExtractor",
    "timestamp.field": "response.generatedAt|generatedAt",
    "timezone": "UTC",
    "topics.dir": "",
    "topics.regex": "^connect-test-audit-topic$",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false"
  }
}